#!/usr/bin/env bash

# bevent
# Copyright (C) 2015 D630, GNU GPLv3
# <https://github.com/D630/bevent>

# -- DEBUGGING.

#printf '%s (%s)\n' "$BASH_VERSION" "${BASH_VERSINFO[5]}" && exit 0
#set -o xtrace
#exec 2>> ~/bevent.log
#set -o verbose
#set -o noexec
#set -o errexit
#set -o nounset
#set -o pipefail
#trap '(read -p "[$BASH_SOURCE:$LINENO] $BASH_COMMAND?")' DEBUG

#declare vars_base=$(set -o posix ; set)
#fgrep -v -e "$vars_base" < <(set -o posix ; set) | \
#egrep -v -e "^BASH_REMATCH=" \
#         -e "^OPTIND=" \
#         -e "^REPLY=" \
#         -e "^BASH_LINENO=" \
#         -e "^BASH_SOURCE=" \
#         -e "^FUNCNAME=" | \
#less

# -- FUNCTIONS.

Bevent::CheckCoprocs ()
{
        typeset -i err=1

        if
                (( ${Status[pid_loop_file_coproc]} ))
        then
                Bevent::Status 95 "file" "${Status[pid_loop_file_coproc]}"
                err=11
        else
                err=10
        fi

        if
                (( ${Status[pid_loop_period_coproc]} ))
        then
                Bevent::Status 95 "period" "${Status[pid_loop_period_coproc]}"
                err=${err}1
        else
                err=${err}0
        fi

        return "$err"
}

Bevent::CreateLog ()
{
        Bevent::Status 93 "${Options[file_log]}"
        >> "${Options[file_log]}"
}

Bevent::Help ()
{
        { typeset h=$(</dev/fd/0) ; } <<'HELP'
Usage:
        bevent <options> [<arguments>]

Options:
        -f                      Work with file events via inotifywait(1)
        -h                      Show this instruction
        -i <info>               Input for postprocessing the inotifywait(1)
                                output. Used with option -f
        -k                      Kill any coprocess and purge the spool file
        -C                      Indicate to set up an event loop in a coprocess
                                Used with options -[fp]
        -p                      Work with time events having periods configured
        -v                      Print version

Arguments:
        <info>                  See Manpage of inotifywait(1):
                                %w|%:e|%f

Environment variables:
        BEVENT_LOG_FILE         ${XDG_DATA_HOME}/bevent/bevent.log
        BEVENT_RC_FILE          ${XDG_CONFIG_HOME}/bevent/bevent.rc
        BEVENT_SPOOL_FILE       ${XDG_DATA_HOME}/bevent/bevent.spool

Configs:
        Bevents[<int>_command]  Command list. Executed via setsid(1)
        Bevents[<int>_exclude]  BRE used with grep(1) to select non-matching
                                files in a watched folder. Delimiter: semicolon
                                (;)
        Bevents[<int>_file]     Watched filenames. Delimiter: vertical bar (|)
        Bevents[<int>_name]     Name of the connected subscripts
        Bevents[<int>_period]   Period in seconds
        Bevents[<int>_symbol]   Names of the inotify events. Delimiter: colon
                                (:)
        Options[delay]          Delay of the time loop in seconds
        Options[file_log]       Logfile
        Options[file_spool]     Spoolfile
HELP

        printf '%s\n' "$h"
}

Bevent::Kill ()
{
        if
                [[ -n ${Status[file_spool]} && -f ${Status[file_spool]} ]]
        then
                Bevent::Status 89 "${Status[file_spool]}"
                command sed -i '/^Status\[/d' "${Status[file_spool]}" 2>/dev/null
        fi

        typeset p
        for p in ${Status[pid_loop_file_coproc]} ${Status[pid_loop_period_coproc]}
        do
                Bevent::Status 90 "$p"
                command pkill -TERM -P "$p"
        done
}

Bevent::CoprocFile ()
{
        Bevent::Prepare || return 1

        typeset -a \
                events_names \
                excludes \
                files \
                patterns \
                watched;

        typeset \
                event_number \
                job \
                info;

        shopt -s extglob

        events_names=( ${!Bevents[@]} )
        files=(
                ${events_names[@]//+([0-9])_@(command|exclude|function|name|period|symbol|time_last)/}
        )
        excludes=(
                ${events_names[@]//+([0-9])_@(command|file|function|name|period|symbol|time_last)/}
        )

        shopt -u extglob

        if
                (( ${#files[@]} ))
        then
                while
                        IFS='_' read -r event_number _
                do
                        while
                                IFS= read -r -d ';'
                        do
                                patterns+=( "$REPLY" )
                        done < <(
                                printf "%s;\n" "${Bevents[${event_number}_exclude]}"
                        )
                        while
                                IFS= read -r -d '|'
                        do
                                watched+=( "$REPLY" )
                        done < <(
                                printf "%s|\n" "${Bevents[${event_number}_file]}"
                        )
                done < <(
                        printf '%s\n' "${files[@]}"
                )
                Bevent::Postpare
                coproc _loop_file {
                        #trap 'Bevent::Kill' INT TERM QUIT EXIT
                        if
                                (( ${#excludes[@]} && ${#patterns[@]} ))
                        then
                                printf '%s\n' "${watched[@]}" \
                                | command grep -vf <(
                                        printf '%s\n' "${patterns[@]}"
                                )
                        else
                                printf '%s\n' "${watched[@]}"
                        fi \
                        | tee >(Bevent::Status 88 $(</dev/fd/0)) \
                        | exec inotifywait -qm --format '%w|%:e|%f' --fromfile - \
                        | {
                                while
                                        read -r
                                do
                                        "${BASH_SOURCE[0]}" -fi "$REPLY"
                                        err=$?
                                        (( err == 100 )) && {
                                                source "${Status[file_spool]}" 2>/dev/null
                                                ( exec "${BASH_SOURCE[0]}" -Cfp & )
                                                Bevent::Kill
                                        }
                                done
                        }
                }
                Status[pid_loop_file_coproc]=$_loop_file_PID
                Bevent::Status 96 "file" "$_loop_file_PID"
                printf 'Status[pid_loop_file_coproc]=%s\n' "$_loop_file_PID" >> "${Status[file_spool]}"
        else
                Bevent::Status 83
        fi
}

Bevent::CoprocPeriod ()
{
        Bevent::Prepare || return 1
        Bevent::Postpare

        coproc _loop_period {
                #trap 'Bevent::Kill' INT TERM QUIT EXIT
                while
                        command sleep "${Options[delay]}"
                do
                        "${BASH_SOURCE[0]}" -p
                done
        }

        Status[pid_loop_period_coproc]=$_loop_period_PID
        Bevent::Status 96 "period" "$_loop_period_PID"
        printf 'Status[pid_loop_period_coproc]=%d\n' "$_loop_period_PID" >> "${Status[file_spool]}"
}

Bevent::Main ()
{
        typeset -i time_curr
        printf -v time_curr '%(%s)T' -1

        (( $# )) || Bevent::Status 79

        typeset -x +i LC_COLLATE=C

        typeset -A \
                Bevents \
                Functions \
                Options \
                Status;

        if
                [[ -n $BEVENT_RC_FILE ]]
        then
                if
                        [[ -f $BEVENT_RC_FILE ]]
                then
                        source "${Options[file_rc]:=${BEVENT_RC_FILE}}"
                        #unset -v BEVENT_RC_FILE
                else
                        Bevent::Status 91 "$BEVENT_RC_FILE"
                fi
        else
                if
                        [[ -f ${Options[file_rc]:=${XDG_CONFIG_HOME}/bevent/bevent.rc} ]]
                then
                        source "${Options[file_rc]}"
                else
                        Bevent::Status 91 "${Options[file_rc]}"
                fi
        fi

        if
                [[ -n $BEVENT_LOG_FILE ]]
        then
                Options[file_log]=$BEVENT_LOG_FILE
                #unset -v BEVENT_LOG_FILE
        else
                Options[file_log]=${Options[file_log]:-${XDG_DATA_HOME}/bevent/bevent.log}
        fi

        if
                [[ -n $BEVENT_SPOOL_FILE ]]
        then
                Options[file_spool]=$BEVENT_SPOOL_FILE
                #unset -v BEVENT_SPOOL_FILE
        else
                Options[file_spool]=${Options[file_spool]:-${XDG_DATA_HOME}/bevent/bevent.spool}
        fi

        command mkdir -vp -- \
                "${Options[file_log]%/*}" \
                "${Options[file_spool]%/*}";

        Options[delay]=${Options[delay]:-60}

        typeset \
                opt \
                opts=:Cfhi:kpv;

        typeset -i j="$# - 1"

        while
                getopts $opts opt
        do
                case $opt in
                f)
                        Functions[f]=$(( j++ ))
                ;;
                i)
                        if
                                [[ $OPTARG == -* ]]
                        then
                                Bevent::Status 86 "$opt"
                        elif
                                [[ $OPTARG == [${opts//:/}] ]]
                        then
                                Bevent::Status 87 "$OPTARG"
                        else
                                Functions[i]=$OPTARG
                        fi
                ;;
                h)
                        Bevent::Help
                        exit $?
                ;;
                k)
                        Functions[k]=$(( j++ ))
                ;;
                C)
                        Functions[C]=$(( j++ ))
                ;;
                p)
                        Functions[p]=$(( j++ ))
                ;;
                v)
                        Bevent::Version
                        exit $?
                ;;
                :)
                        Bevent::Status 86 "$OPTARG"
                ;;
                \?)
                        Bevent::Status 80 "$OPTARG"
                esac
        done

        Functions[${Functions[f]:--}]=Bevent::Files
        Functions[${Functions[k]:--}]=Bevent::Kill
        Functions[${Functions[C]:--}]=Bevent::Coproc
        Functions[${Functions[p]:--}]=Bevent::Periods

        source "${Options[file_spool]}" 2>/dev/null

        typeset -i err=

        if
                [[ -n ${Functions[C]} && -z ${Functions[f]}${Functions[p]} ]]
        then
                Bevent::Status 84
        elif
                [[ -n ${Functions[k]} ]]
        then
                Functions=()
                Functions[0]=Bevent::Kill
        elif
                [[
                        -n ${Functions[C]} &&
                        -n ${Functions[f]} &&
                        -n ${Functions[p]}
                ]]
        then
                Bevent::CheckCoprocs
                err=$?
                if
                        (( err == 100 ))
                then
                        Functions=()
                        Functions[0]=Bevent::CoprocPeriod
                        Functions[1]=Bevent::CoprocFile
                else
                        exit 95
                fi
        elif
                [[ -n ${Functions[C]} && -n ${Functions[f]} ]]
        then
                Bevent::CheckCoprocs
                err=$?
                if
                        (( err == 110 || err == 111 ))
                then
                        exit 95
                else
                        Functions=()
                        Functions[0]=Bevent::CoprocFile
                fi
        elif
                [[ -n ${Functions[C]} && -n ${Functions[p]} ]]
        then
                Bevent::CheckCoprocs
                err=$?
                if
                        (( err == 101 || err == 111 ))
                then
                        exit 95
                else
                        Functions=()
                        Functions[0]=Bevent::CoprocPeriod
                fi
        elif
                [[
                        ( -n ${Functions[f]} && -n ${Functions[p]} ) ||
                        -n ${Functions[f]}
                ]]
        then
                Options[noloop]=noloop
                if
                        [[ -n ${Functions[i]} ]]
                then
                        Functions[${Functions[f]}]="Bevent::Files ${Functions[i]}"
                else
                        Bevent::Status 85
                fi
        elif
                [[ -n ${Functions[p]} ]]
        then
                Options[noloop]=noloop
        fi

        unset -v \
                Functions[--] \
                Functions[f] \
                Functions[i] \
                Functions[k] \
                Functions[C] \
                Functions[p];

        exec >>"${Options[file_log]}" 2>&1

        for (( opt=0 ; opt < $j ; opt++ ))
        do
                [[ -n ${Functions[$opt]} ]] && ${Functions[$opt]}
        done
}

Bevent::Postpare ()
{
        if
                (( ${#spool[@]} ))
        then
                printf '%s\n' "${spool[@]}" > "${Options[file_spool]}"
        else
                command sed -i '/^Status\[/d' "${Status[file_spool]}" 2>/dev/null
        fi

        Status[file_rc]=${Status[file_rc]:-${Options[file_rc]}}
        Status[file_spool]=${Status[file_spool]:-${Options[file_spool]}}

        typeset e
        for e in "${!Status[@]}"
        do
                printf 'Status[%s]=%s\n' "$e" "${Status[$e]}"
        done >> "${Status[file_spool]}"
}

Bevent::Prepare ()
{
        Status[file_spool]=${Options[file_spool]}
        [[ -z ${Options[noloop]} ]] && Bevent::CreateLog
}

Bevent::Status ()
{
        typeset s

        case $1 in
        79) printf -v s '%s %s:Error:%s: No command specified\n' "$time_curr" "${BASH_SOURCE[0]}" "$1"                                                  ;;
        80) printf -v s '%s %s:Error:%s: Unknown flag: -%s\n' "$time_curr" "${BASH_SOURCE[0]}" "$1" "$2"                                                ;;
        81) printf -v s '%s %s:Error:%s: Config file missing\n' "$time_curr" "${BASH_SOURCE[0]}" "$1"                                                   ;;
        82) printf -v s '%s %s:Error:%s: Anacronistic commands missing\n' "$time_curr" "${BASH_SOURCE[0]}" "$1"                                         ;;
        83) printf      '%s %s:Error:%s: Inotify filenames missing\n' "$time_curr" "${BASH_SOURCE[0]}" "$1"                                             ;;
        84) printf -v s '%s %s:Error:%s: No loop specified\n' "$time_curr" "${BASH_SOURCE[0]}" "$1"                                                     ;;
        85) printf -v s '%s %s:Error:%s: No event information specified\n' "$time_curr" "${BASH_SOURCE[0]}" "$1"                                        ;;
        86) printf -v s '%s %s:Error:%s: Option -%s requires an argument\n' "$time_curr" "${BASH_SOURCE[0]}" "$1" "$2"                                  ;;
        87) printf -v s '%s %s:Error:%s: Wrong argument: %s\n' "$time_curr" "${BASH_SOURCE[0]}" "$1" "$2"                                               ;;
        88) printf      '%s %s:Info:%s: Watching: %s\n' "$time_curr" "${BASH_SOURCE[0]}" "$1" "${*:2}"                                                  ;;
        89) printf      '%s %s:Info:%s: Removing status information in spool: %s\n' "$time_curr" "${BASH_SOURCE[0]}" "$1" "$2"                          ;;
        90) printf      '%s %s:Info:%s: Killing pid: %s\n' "$time_curr" "${BASH_SOURCE[0]}" "$1" "$2"                                                   ;;
        91) printf -v s '%s %s:Error:%s: Conf File does not exist or is not a regular file: %s\n' "$time_curr" "${BASH_SOURCE[0]}" "$1" "$2"            ;;
        93) printf      '%s %s:Info:%s: Creating new logs in: %s\n' "$time_curr" "${BASH_SOURCE[0]}" "$1" "$2"                                          ;;
        94) printf      '%s %s:Info:%s: Processing command %s: %s\n' "$time_curr" "${BASH_SOURCE[0]}" "$1" "$2" "$3"                                    ;;
        95) printf      '%s %s:Info:%s: Coproc (%s) has already been started with pid: %s\n' "$time_curr" "${BASH_SOURCE[0]}" "$1" "$2" "$3"            ;;
        96) printf      '%s %s:Info:%s: Creating coproc (%s) with pid: %s\n' "$time_curr" "${BASH_SOURCE[0]}" "$1" "$2" "$3"                            ;;
        97) printf      '%s %s:Error:%s: Job is unknown: %s\n' "$time_curr" "${BASH_SOURCE[0]}" "$1" "$2"                                               ;;
        99) printf -v s '%s %s:Info:%s: Restarting coproc (file) with pid: %s\n' "$time_curr" "${BASH_SOURCE[0]}" "$1" "$2"                             ;;
        100) printf -v s '%s %s:Info:%s: Restarting coprocs (file, period) with pids: %s, %s\n' "$time_curr" "${BASH_SOURCE[0]}" "$1" "$2" "$3"         ;;
        102) printf -v s '%s %s:Error:%s: Bevent symbols missing\n' "$time_curr" "${BASH_SOURCE[0]}" "$1"                                                ;;
        esac 1>&2

        [[ -z $s ]] || {
                printf '%s' "$s" 1>&2
                exit "$1"
        }
}

Bevent::Files ()
{
        typeset \
                event_number \
                file \
                path \
                s \
                symbol;

        typeset -a \
                commands \
                events_names \
                files \
                symbols;

        IFS='|' read -r path symbol file <<< "$@"

        if
                [[ $symbol == DELETE_SELF && -n ${Status[pid_loop_file_coproc]} ]]
        then
                if
                        (( ${Status[pid_loop_period_coproc]} ))
                then
                        Bevent::Status 100 "${Status[pid_loop_file_coproc]}" "${Status[pid_loop_period_coproc]}"
                else
                        Bevent::Kill
                        Bevent::Status 99 "${Status[pid_loop_file_coproc]}"
                fi
        fi

        shopt -s extglob

        events_names=( ${!Bevents[@]} )
        files=(
                ${events_names[@]//+([0-9])_@(command|exclude|function|name|period|symbol|time_last)/}
        )
        symbols=(
                ${events_names[@]//+([0-9])_@(command|exclude|file|function|name|period|time_last)/}
        )
        commands=(
                ${events_names[@]//+([0-9])_@(exclude|file|function|name|period|symbol|time_last)/}
        )

        shopt -u extglob

        if
                (( ${#files[@]} == 0 ))
        then
                Bevent::Status 83
        elif
                (( ${#commands[@]} == 0 ))
        then
                Bevent::Status 82
        elif
                (( ${#symbols[@]} == 0 ))
        then
                Bevent::Status 102
        else
                Status[time_run_last_file]=$time_curr
                while
                        IFS='_' read -r event_number _
                do
                        while
                                IFS= read -r -d '|'
                        do
                                [[ $REPLY =~ $path ]] && {
                                        for s in ${Bevents[${event_number}_symbol]//:/ }
                                        do
                                                [[ $symbol == $s ]] && {
                                                        Bevent::Status 94 "${Bevents[${event_number}_name]}" "${Bevents[${event_number}_command]}"
                                                        Bevent::Run
                                                        break
                                                }
                                        done
                                        s=
                                }
                        done < <(
                                printf '%s|\n' "${Bevents[${event_number}_file]}"
                        )
                done < <(
                        printf '%s\n' "${files[@]}"
                )
                Bevent::Postpare
        fi
}

Bevent::Periods ()
{
        typeset -a \
                commands \
                spool;

        typeset -i \
                event_number \
                time_diff;

        shopt -s extglob

        commands=( ${!Bevents[@]} )
        commands=(
                ${commands[@]//+([0-9])_@(exclude|file|function|name|period|symbol|time_last)/}
        )

        (( ${#commands[@]} )) ||  Bevent::Status 82

        shopt -u extglob

        while
                IFS='_' read -r event_number _
        do
                time_diff="time_curr - ${Bevents[${event_number}_time_last]:-0}"
                if
                        (( ${Bevents[${event_number}_period]} ))
                then
                        Status[time_run_last_period]=$time_curr
                        if
                                (( time_diff >= ${Bevents[${event_number}_period]} ))
                        then
                                Bevent::Status 94 "${Bevents[${event_number}_name]}" "${Bevents[${event_number}_command]}"
                                Bevent::Run
                                spool+=(
                                        "Bevents[${event_number}_time_last]=${time_curr}"
                                )
                        else
                                spool+=(
                                        "Bevents[${event_number}_time_last]=${Bevents[${event_number}_time_last]}"
                                )
                        fi
                else
                        continue
                fi
        done < <(
                printf '%s\n' "${commands[@]}" \
                | sort -n
        )

        Bevent::Postpare
}

Bevent::Run ()
if
        ${Bevents[${event_number}_function]:-false} 2>/dev/null &&
        typeset -F "${Bevents[${event_number}_command]}" 1>/dev/null 2>&1
then
        (
                typeset -xf "${Bevents[${event_number}_command]}"
                command setsid bash -c "${Bevents[${event_number}_command]}" &
        )
else
        ( command setsid "${Bevents[${event_number}_command]}" & )
fi

Bevent::Version ()
{
        printf 'v%s\n' "0.1.11"
}

# -- MAIN.

Bevent::Main "$@"

# vim: set ts=8 sw=8 tw=0 et :
